### PR TITLE
Documentation about apply

### PR DESCRIPTION
**Pull request by dakaza98**
During Dkå 20's year we have documented apply.utn.se but we have been a bit lazy with adding it to this repository but now here it is. This documentation contains instruction videos for the various parts of apply (recorded by @SimonJaklovsky). It also features an introduction page that introduces several important key concepts

### CODE REVIEW

**Comment by Dekker1** [comment]
Hey! It's great to see that you guys are expanding the documentation website! I'm really happy it caught on!

I just saw this one come by in my email and just wanted to note that it might not be a good idea to include video files in a git repository. As you might know, git doesn't handle binary formats particularly well: any change will require you to include a full new file in the repository, whenever you then checkout the repository all these files will automatically be downloaded (even if the files later get removed).

One solution is to use Git's Large File Storage (LFS), but it can be a bit messy. The easier solution might be to use a dedicated streaming website like Vimeo or YouTube. 

(If you decide to take my advice, then please remember to amend/rebase so the file never enter the repository, otherwise you'll still have to download the videos whenever you checkout the repository)

**Comment by Antonfogelberg** [comment]
I think youtube would be perfect for this! Will look into if UTN or Digitalkå has a channel that we can use instead!

**Comment by dakaza98** [comment]
I have now removed all videos from the git history. Now they just need to be uploaded to youtube and have their link added to the documentation. I have the videos on my onedrive

**Comment by Dekker1** [comment]
Although it might look like the videos are no longer part of the repository, they are actually still there. The videos are added in one commit and then removed in another commit. Because git will keep the full history of the repository, it still contains the video files, even when they are no longer used. (This is the big problem with git.

To fully remove the videos, you have to rebase your git branch. Using this you can either squash all commits together into a single commit that contains all changes (the easy approach) or you can edit commits and remove commits to allow you to change history to make it as if the videos were never added.

If you are not comfortable using rebasing, then another easy approach is to just start a new branch and copy the changes (that you want to keep) over to that branch.

**Review by Antonfogelberg — APPROVED** [review]
Made use of the embedded videos using iframes. The videos are now stored on google drive.

**Pull request merged**
