### PR TITLE
Add name to Hall of Fame

### PR DESCRIPTION
**Pull request by perenstrom**
Just stumbled on these docs by chance. Great to see that stuff is being documented properly. And I love to see a hall of fame with some famous names on it. And I wanna take the opportunity to be un-Swedish about the whole thing and enter myself into the list. I hope that's alright. :) I also fixed a typo in Åke's name.

### CODE REVIEW

**Comment by Dekker1** [comment]
Thank you for contributing your name to the list. The idea behind the Hall of Fame was always to work our way back to include as many names as possible. I was always disappointed that I didn't have the time (or the right connections) to discover more of the past.

**Comment by perenstrom** [comment]
@Dekker1 Do you have privileges to approve and merge? :)

**Comment by dakaza98** [comment]
Hej per! Super nice that you wanted to contribute to the hall of fame! @Antonfogelberg can merge your PR

**Review by Antonfogelberg — APPROVED** [review]
Nice with another name to list!

**Comment by Antonfogelberg** [comment]
Changes should now be live!

**Pull request merged**
